# Generated by Django 6.0.7 on 2026-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
