# Generated by Django 6.0.7 on 2026-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
