# Generated by Django 6.0.7 on 2026-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise',
            field=models.CharField(blank=True, help_text='Example: Urban Planning, Climate Change, GIS', max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='google_scholar',
            field=models.URLField(blank=True, verbose_name='Google Scholar'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='orcid',
            field=models.URLField(blank=True, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='researchgate',
            field=models.URLField(blank=True, verbose_name='ResearchGate'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website',
            field=models.URLField(blank=True, verbose_name='Personal Website'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='biography',
            field=models.TextField(help_text='Supports paragraphs. Use separate fields below for links.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=150),
        ),
    ]
