# Generated by Django 6.0.7 on 2026-07-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
